In [1]:
!pip install pymysql
import pandas as pd
import pymysql
from sqlalchemy import create_engine

Requirement already satisfied: pymysql in .\anaconda3\Lib\site-packages (1.2.0)

In [ ]:
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)
tables = pd.read_sql_query("SHOW TABLES", engine)
tables

  Tables_in_vendor_db
0     begin_inventory
1       end_inventory
2     purchase_prices
3           purchases
4               sales
5      vendor_invoice

In [3]:
for table in tables['Tables_in_vendor_db']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records:',pd.read_sql(f"select count(*) as count from {table}",engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records:     count
0  206529
-------------------------------------------------- end_inventory --------------------------------------------------
Count of records:     count
0  224489
-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records:    count
0  12261
-------------------------------------------------- purchases --------------------------------------------------
Count of records:      count
0  2372474
-------------------------------------------------- sales --------------------------------------------------
Count of records:       count
0  12825363
-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records:    count
0   5543

In [4]:
for table in tables['Tables_in_vendor_db']:
    print('-'*50, f'{table}', '-'*50)

    count = pd.read_sql(
        f"SELECT COUNT(*) FROM {table}",
        engine
    ).iloc[0, 0]

    print("Count of records:", count)
    display(pd.read_sql(f"select * from {table} limit 5",engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,False,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,False,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,False,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,False,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [5]:
purchases = pd.read_sql("select * from purchases where VendorNumber =4466",engine)
purchases

,False,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,8091,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,8092,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,2314214,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,2314215,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,2314216,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,2314217,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,2314218,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [6]:
purchase_prices = pd.read_sql("select * from purchase_prices where VendorNumber =4466",engine)
purchase_prices

,False,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,1197,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,1212,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,9962,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [7]:
sales = pd.read_sql("select * from sales where VendorNo =4466",engine)

In [8]:
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [9]:
vendor_invoice = pd.read_sql("select * from vendor_invoice where VendorNumber=4466",engine)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [10]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [11]:
sales.groupby(['Brand','SalesPrice'])[['SalesDollars','SalesQuantity']].sum()

                  SalesDollars  SalesQuantity
Brand SalesPrice
3140  12.99           50531.10           3890
5215  12.99           60416.49           4651
5255  12.99           79187.04           6096

Information about the tables

Purchases table: Contains actual purchase data, including:
Date of purchase
Products (brands) purchased by vendors
Amount paid (in dollars)
Quantity purchased.

Purchase price column: This is derived from the purchase_prices table, which provides product-wise actual and purchase prices.
The combination of vendor and brand is unique in this table.
    
Vendor_invoice table: Aggregates data from the purchases table, summarizing:
Quantity
Dollar amounts
Freight costs
It maintains uniqueness based on vendor and PO number.
    
Sales table: Contains actual sales transactions, including:
Brands purchased/sold by vendors
Quantity sold
Selling price
Revenue earned.


Summary table required for analysis
Because the required data is distributed across different tables, a summary table needs to contain:
Purchase transactions made by vendors
Sales transaction data
Freight costs for each vendor
Actual product prices from vendors.

In [13]:
freight_summary = pd.read_sql("select VendorNumber ,sum(Freight) as FreightCost From vendor_invoice group by VendorNumber",engine)
freight_summary

     VendorNumber  FreightCost
0             105        62.39
1            4466       793.91
2             388       211.74
3             480     89286.27
4             516      8510.41
..            ...          ...
121        201359         0.09
122          4901         0.72
123         90059        74.84
124          5083        10.68
125            54         0.48

[126 rows x 2 columns]

In [14]:
purchases.columns

Index(['False', 'InventoryId', 'Store', 'Brand', 'Description', 'Size',
       'VendorNumber', 'VendorName', 'PONumber', 'PODate', 'ReceivingDate',
       'InvoiceDate', 'PayDate', 'PurchasePrice', 'Quantity', 'Dollars',
       'Classification'],
      dtype='str')

In [15]:
purchase_prices.columns

Index(['False', 'Brand', 'Description', 'Price', 'Size', 'Volume',
       'Classification', 'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='str')

In [16]:
purchase_summary = pd.read_sql("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price,
    SUM(p.Quantity) AS total_purchase_quantity,
    SUM(p.Dollars) AS total_purchase_dollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
where p.PurchasePrice>0
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY total_purchase_dollars
""", engine)

In [17]:
purchase_summary

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,Price,total_purchase_quantity,total_purchase_dollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1.0,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1.0,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2.0,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6.0,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2.0,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109.0,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682.0,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407.0,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038.0,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080.0,3811251.60

In [18]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [19]:
pd.read_sql("""select
VendorNo,Brand,
sum(SalesDollars) as totalsalesdollars,
sum(SalesPrice) as totalsalesprice,
sum(salesQuantity) as totalsalesquantity,
sum(ExciseTax) as totalexcisetax
from sales
group by VendorNo , Brand
order by totalsalesdollars""",engine)

,VendorNo,Brand,totalsalesdollars,totalsalesprice,totalsalesquantity,totalexcisetax
0,8004,5287,9.800000e-01,0.98,2.0,0.10
1,9206,2773,9.900000e-01,0.99,1.0,0.05
2,3924,9123,1.980000e+00,0.99,2.0,0.10
3,3252,3933,1.980000e+00,0.99,2.0,0.10
4,10050,3623,1.980000e+00,1.98,2.0,0.10
...,...,...,...,...,...,...
11267,3960,3545,4.223108e+06,545778.28,135838.0,249587.83
11268,3960,4261,4.475973e+06,420050.01,200412.0,368242.80
11269,17035,8068,4.538121e+06,461140.15,187140.0,343854.07
11270,4425,3405,4.819073e+06,561512.37,160247.0,294438.66
11271,1128,1233,5.101920e+06,672819.31,142049.0,260999.20

In [39]:
vendor_sales_summary = pd.read_sql_query("""
WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY p.VendorNumber,
             p.VendorName,
             p.Brand,
             p.Description,
             p.PurchasePrice,
             pp.Price,
             pp.Volume
),

SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost

FROM PurchaseSummary ps

LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand

LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
""", engine)

In [41]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                       str
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [43]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [45]:
vendor_sales_summary['VendorName'].unique()

<ArrowStringArray>
[            'ALTAMAR BRANDS LLC         ',
             'AMERICAN VINTAGE BEVERAGE  ',
             'BACARDI USA INC            ',
             'BANFI PRODUCTS CORP        ',
             'BLACK PRINCE DISTILLERY INC',
             'BROWN-FORMAN CORP          ',
             'BULLY BOY DISTILLERS       ',
             'CALEDONIA SPIRITS INC      ',
             'CAMPARI AMERICA            ',
             'CANDIA VINEYARDS           ',
 ...
             'FULCHINO VINEYARD INC      ',
                         'UNCORKED       ',
 'IRA GOLDMAN AND WILLIAMS, LLP          ',
             'GILMANTON WINERY & VINEYARD',
             'FLAVOR ESSENCE INC         ',
             'BLACK COVE BEVERAGES       ',
             'VINEYARD BRANDS LLC        ',
             'BLACK ROCK SPIRITS LLC     ',
             'STARK BREWING COMPANY      ',
             'LAUREATE IMPORTS CO        ']
Length: 129, dtype: str

In [47]:
vendor_sales_summary['Description'].unique()

<ArrowStringArray>
[   'Tequila Ocho Plata Fresno', 'TGI Fridays Ultimte Mudslide',
 'TGI Fridays Long Island Iced',          'Bombay Sapphire Gin',
            'Bacardi 151 Proof',         'Bacardi Superior Rum',
   'Grey Goose Le Citron Vodka',    'Grey Goose L'Orange Vodka',
     'Dewars Special RSV 12-Yr',     'Bacardi Dragon Berry Rum',
 ...
 'Medici Ermete Concerto Lmbrs',     'Dievole Chianti Classico',
     'Barone Ricasoli Castello',       'Roth Estate Pinot Noir',
           'Hedges CMS Svgn Bl', 'Priest Ranch Sauvignon Blanc',
               'Ch Maycott Red',   'Abraham Bowman Ltd Edition',
  'The Divining Rod Pinot Noir',            'Straw Boys Poitin']
Length: 9651, dtype: str

In [51]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [53]:
vendor_sales_summary.fillna(0, inplace=True)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,105,ALTAMAR BRANDS LLC,8412,Tequila Ocho Plata Fresno,35.71,49.99,750.0,320.0,11427.20,307.0,15346.93,12947.41,242.15,62.39
1,4466,AMERICAN VINTAGE BEVERAGE,5255,TGI Fridays Ultimte Mudslide,9.35,12.99,1750.0,6215.0,58110.25,6096.0,79187.04,51180.60,11204.28,793.91
2,4466,AMERICAN VINTAGE BEVERAGE,5215,TGI Fridays Long Island Iced,9.41,12.99,1750.0,4923.0,46325.43,4651.0,60416.49,41542.02,8548.96,793.91
3,480,BACARDI USA INC,3348,Bombay Sapphire Gin,22.38,29.99,1750.0,57349.0,1283470.62,56888.0,1766391.12,460087.95,104524.54,89286.27
4,480,BACARDI USA INC,8358,Bacardi 151 Proof,14.49,19.99,750.0,7071.0,102458.79,8065.0,161219.35,87396.28,6352.66,89286.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,4425,MARTIGNETTI COMPANIES,28007,Priest Ranch Sauvignon Blanc,12.41,18.99,750.0,120.0,1489.20,0.0,0.00,0.00,0.00,144929.24
10688,7153,PINE STATE TRADING CO,26508,Ch Maycott Red,6.81,10.49,750.0,1.0,6.81,1.0,10.49,10.49,0.11,15884.82
10689,8004,SAZERAC CO INC,2936,Abraham Bowman Ltd Edition,53.02,69.99,750.0,18.0,954.36,4.0,279.96,69.99,3.15,50293.62
10690,2000,SOUTHERN WINE & SPIRITS NE,26266,The Divining Rod Pinot Noir,11.56,16.99,750.0,132.0,1525.92,2.0,33.98,16.99,0.22,19016.59
10691,9165,ULTRA BEVERAGE COMPANY LLP,1073,Straw Boys Poitin,25.73,34.99,750.0,168.0,4322.64,0.0,0.00,0.00,0.00,68054.70

In [55]:
vendor_sales_summary['VendorName'] =vendor_sales_summary['VendorName'].str.strip()

0                ALTAMAR BRANDS LLC
1         AMERICAN VINTAGE BEVERAGE
2         AMERICAN VINTAGE BEVERAGE
3                   BACARDI USA INC
4                   BACARDI USA INC
                    ...
10687         MARTIGNETTI COMPANIES
10688         PINE STATE TRADING CO
10689                SAZERAC CO INC
10690    SOUTHERN WINE & SPIRITS NE
10691    ULTRA BEVERAGE COMPANY LLP
Name: VendorName, Length: 10692, dtype: str

In [57]:
vendor_sales_summary['Grossprofit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [59]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,Grossprofit
0,105,ALTAMAR BRANDS LLC,8412,Tequila Ocho Plata Fresno,35.71,49.99,750.0,320.0,11427.20,307.0,15346.93,12947.41,242.15,62.39,3919.73
1,4466,AMERICAN VINTAGE BEVERAGE,5255,TGI Fridays Ultimte Mudslide,9.35,12.99,1750.0,6215.0,58110.25,6096.0,79187.04,51180.60,11204.28,793.91,21076.79
2,4466,AMERICAN VINTAGE BEVERAGE,5215,TGI Fridays Long Island Iced,9.41,12.99,1750.0,4923.0,46325.43,4651.0,60416.49,41542.02,8548.96,793.91,14091.06
3,480,BACARDI USA INC,3348,Bombay Sapphire Gin,22.38,29.99,1750.0,57349.0,1283470.62,56888.0,1766391.12,460087.95,104524.54,89286.27,482920.50
4,480,BACARDI USA INC,8358,Bacardi 151 Proof,14.49,19.99,750.0,7071.0,102458.79,8065.0,161219.35,87396.28,6352.66,89286.27,58760.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,4425,MARTIGNETTI COMPANIES,28007,Priest Ranch Sauvignon Blanc,12.41,18.99,750.0,120.0,1489.20,0.0,0.00,0.00,0.00,144929.24,-1489.20
10688,7153,PINE STATE TRADING CO,26508,Ch Maycott Red,6.81,10.49,750.0,1.0,6.81,1.0,10.49,10.49,0.11,15884.82,3.68
10689,8004,SAZERAC CO INC,2936,Abraham Bowman Ltd Edition,53.02,69.99,750.0,18.0,954.36,4.0,279.96,69.99,3.15,50293.62,-674.40
10690,2000,SOUTHERN WINE & SPIRITS NE,26266,The Divining Rod Pinot Noir,11.56,16.99,750.0,132.0,1525.92,2.0,33.98,16.99,0.22,19016.59,-1491.94
10691,9165,ULTRA BEVERAGE COMPANY LLP,1073,Straw Boys Poitin,25.73,34.99,750.0,168.0,4322.64,0.0,0.00,0.00,0.00,68054.70,-4322.64

In [63]:
vendor_sales_summary['ProfitMargin']=vendor_sales_summary['Grossprofit']/vendor_sales_summary['TotalSalesDollars']

In [65]:
vendor_sales_summary['StockTurnover']=vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [67]:
vendor_sales_summary['SalestoPurchaseRatio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [79]:
import numpy as np
vendor_sales_summary.fillna(0, inplace=True)

vendor_sales_summary['ProfitMargin'] = (
    vendor_sales_summary['Grossprofit'] /
    vendor_sales_summary['TotalSalesDollars']
)

vendor_sales_summary['StockTurnover'] = (
    vendor_sales_summary['TotalSalesQuantity'] /
    vendor_sales_summary['TotalPurchaseQuantity']
)

vendor_sales_summary['SalestoPurchaseRatio'] = (
    vendor_sales_summary['TotalSalesDollars'] /
    vendor_sales_summary['TotalPurchaseDollars']
)

vendor_sales_summary.replace([np.inf, -np.inf], 0, inplace=True)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,Grossprofit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,105,ALTAMAR BRANDS LLC,8412,Tequila Ocho Plata Fresno,35.71,49.99,750.0,320.0,11427.20,307.0,15346.93,12947.41,242.15,62.39,3919.73,0.255408,0.959375,1.343018
1,4466,AMERICAN VINTAGE BEVERAGE,5255,TGI Fridays Ultimte Mudslide,9.35,12.99,1750.0,6215.0,58110.25,6096.0,79187.04,51180.60,11204.28,793.91,21076.79,0.266165,0.980853,1.362703
2,4466,AMERICAN VINTAGE BEVERAGE,5215,TGI Fridays Long Island Iced,9.41,12.99,1750.0,4923.0,46325.43,4651.0,60416.49,41542.02,8548.96,793.91,14091.06,0.233232,0.944749,1.304175
3,480,BACARDI USA INC,3348,Bombay Sapphire Gin,22.38,29.99,1750.0,57349.0,1283470.62,56888.0,1766391.12,460087.95,104524.54,89286.27,482920.50,0.273394,0.991961,1.376261
4,480,BACARDI USA INC,8358,Bacardi 151 Proof,14.49,19.99,750.0,7071.0,102458.79,8065.0,161219.35,87396.28,6352.66,89286.27,58760.56,0.364476,1.140574,1.573504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,4425,MARTIGNETTI COMPANIES,28007,Priest Ranch Sauvignon Blanc,12.41,18.99,750.0,120.0,1489.20,0.0,0.00,0.00,0.00,144929.24,-1489.20,0.000000,0.000000,0.000000
10688,7153,PINE STATE TRADING CO,26508,Ch Maycott Red,6.81,10.49,750.0,1.0,6.81,1.0,10.49,10.49,0.11,15884.82,3.68,0.350810,1.000000,1.540382
10689,8004,SAZERAC CO INC,2936,Abraham Bowman Ltd Edition,53.02,69.99,750.0,18.0,954.36,4.0,279.96,69.99,3.15,50293.62,-674.40,-2.408916,0.222222,0.293348
10690,2000,SOUTHERN WINE & SPIRITS NE,26266,The Divining Rod Pinot Noir,11.56,16.99,750.0,132.0,1525.92,2.0,33.98,16.99,0.22,19016.59,-1491.94,-43.906416,0.015152,0.022269
10691,9165,ULTRA BEVERAGE COMPANY LLP,1073,Straw Boys Poitin,25.73,34.99,750.0,168.0,4322.64,0.0,0.00,0.00,0.00,68054.70,-4322.64,0.000000,0.000000,0.000000

In [81]:
vendor_sales_summary.to_sql(
    'vendor_sales_summary',
    con=engine,
    if_exists='replace',
    index=False
)

10692

In [87]:
summary = pd.read_sql("select * from vendor_sales_summary",engine)
summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,Grossprofit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,105,ALTAMAR BRANDS LLC,8412,Tequila Ocho Plata Fresno,35.71,49.99,750.0,320.0,11427.20,307.0,15346.93,12947.41,242.15,62.39,3919.73,0.255408,0.959375,1.343018
1,4466,AMERICAN VINTAGE BEVERAGE,5255,TGI Fridays Ultimte Mudslide,9.35,12.99,1750.0,6215.0,58110.25,6096.0,79187.04,51180.60,11204.28,793.91,21076.79,0.266165,0.980853,1.362703
2,4466,AMERICAN VINTAGE BEVERAGE,5215,TGI Fridays Long Island Iced,9.41,12.99,1750.0,4923.0,46325.43,4651.0,60416.49,41542.02,8548.96,793.91,14091.06,0.233232,0.944749,1.304175
3,480,BACARDI USA INC,3348,Bombay Sapphire Gin,22.38,29.99,1750.0,57349.0,1283470.62,56888.0,1766391.12,460087.95,104524.54,89286.27,482920.50,0.273394,0.991961,1.376261
4,480,BACARDI USA INC,8358,Bacardi 151 Proof,14.49,19.99,750.0,7071.0,102458.79,8065.0,161219.35,87396.28,6352.66,89286.27,58760.56,0.364476,1.140574,1.573504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,4425,MARTIGNETTI COMPANIES,28007,Priest Ranch Sauvignon Blanc,12.41,18.99,750.0,120.0,1489.20,0.0,0.00,0.00,0.00,144929.24,-1489.20,0.000000,0.000000,0.000000
10688,7153,PINE STATE TRADING CO,26508,Ch Maycott Red,6.81,10.49,750.0,1.0,6.81,1.0,10.49,10.49,0.11,15884.82,3.68,0.350810,1.000000,1.540382
10689,8004,SAZERAC CO INC,2936,Abraham Bowman Ltd Edition,53.02,69.99,750.0,18.0,954.36,4.0,279.96,69.99,3.15,50293.62,-674.40,-2.408916,0.222222,0.293348
10690,2000,SOUTHERN WINE & SPIRITS NE,26266,The Divining Rod Pinot Noir,11.56,16.99,750.0,132.0,1525.92,2.0,33.98,16.99,0.22,19016.59,-1491.94,-43.906416,0.015152,0.022269
10691,9165,ULTRA BEVERAGE COMPANY LLP,1073,Straw Boys Poitin,25.73,34.99,750.0,168.0,4322.64,0.0,0.00,0.00,0.00,68054.70,-4322.64,0.000000,0.000000,0.000000